-keep public class com.crazylegend.subhub.adapters.localVideos.LocalVideoViewHolder { <methods>; }
-keep public class com.crazylegend.subhub.adapters.chooseLanguage.LanguageViewHolder { <methods>; }
-keep public class com.crazylegend.subhub.adapters.subtitles.SubtitlesViewHolder { <methods>; }
-keep public class com.crazylegend.subhub.adapters.folderSources.PickedDirViewHolder { <methods>; }